[package]
name = "rgrok"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.4"
ignore = "0.4.18"
syn = { version = "1.0.75", features = ["parsing", "full"] }
syntect = "4.6.0"
